### DISCUSSION TITLE
RTX 5090 - cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED

### DISCUSSION THREAD

**Discussion by CarzyBilly** [Purfview/whisper-standalone-win#423] [Q&A] [answered]
Hello, I'm a beginner and I have no idea about this code. I'm encountering a problem now.
When I run this command
```
Faster-whisper-xxl.exe test.mkv --language English --model turbo --output_dir "D:\Desktop"
```
Or this command
```
set CUDA_LAUNCH_BLOCKING=1
faster-whisper-xxl.exe test.mkv --language English --model turbo --output_dir "D:\Desktop" --output_format txt --diarize pyannote_v3.1 --num_speakers=4
```
Then the following error will occur:
```
Standalone Faster-Whisper-XXL r245.2 running on: CUDA
Note: 'large-v3' model may produce worse results than 'large-v2'!
Traceback (most recent call last):
 File "D:\whisper-fast-XXL\__main__.py", line 2245, in <module>
 File "D:\whisper-fast-XXL\__main__.py", line 2087, in cli
 File "faster_whisper\transcribe.py", line 1118, in transcribe
 File "faster_whisper\transcribe.py", line 2147, in detect_language
 File "faster_whisper\transcribe.py", line 1719, in encode
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
[PYI-3008:ERROR] Failed to execute script '__main__' due to unhandled exception!
```
My running environment is Windows 11 Pro 24H2, the graphics card is RTX 5090, the driver is 572.70.
I tried using CUDA versions 11.8 and 12.8 respectively, but neither of them could run properly.
I can cooperate with all your tests, can you help me solve this problem?

**Comment by Purfview** [comment, marked as answer]
>RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED

This issue is already reported: https://github.com/Purfview/whisper-standalone-win/issues/403
Use `--compute_type float16` or `-ct float16`

>I can cooperate with all your tests, can you help me solve this problem?

Subscribe to that thread, if I'll need some testing then I'll post there.

**Reply by CarzyBilly** [reply]
Thank you very much, I have solved this problem that has bothered me for several days
