### ISSUE TITLE
Could not load library libcudnn_ops_infer.so.8

### ISSUE THREAD

**Issue by arekgotfryd** [Purfview/whisper-standalone-win#171]
When I run it on WSL Ubuntu like below
`./whisper-faster "chatgpt.mp4" --language=English --model=medium`
I get 
```
Standalone Faster-Whisper r167.4 running on: CUDA


Starting transcription on: chatgpt.mp4

Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Please make sure libcudnn_ops_infer.so.8 is in your library path!
Aborted
```
Even though my system doesn't have Nvidia GPU. 

WSL Ubuntu version
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

I use [Whisper-Faster_r167.4_linux.zip](https://github.com/Purfview/whisper-standalone-win/releases/download/faster-whisper/Whisper-Faster_r167.4_linux.zip)

**Comment by Purfview** [comment]
I've no idea how it reports that you have CUDA when you don't.

What `./whisper-faster --checkcuda` shows?

You can force CPU with `--device=cpu`.

**Comment by arekgotfryd** [comment]
Thanks for the tip with `--device=cpu`!
That solves it.

**Comment by Purfview** [comment]
What ./whisper-faster --checkcuda shows?

**Comment by arekgotfryd** [comment]
CUDA device: 1

**Comment by Purfview** [comment]
And what GPU you have in your system?

> CUDA device: 1

Yeah, reports  that there is 1 CUDA device.

**Comment by arekgotfryd** [comment]
Lol you know what I do have NVIDIA GTX 1050 on windows host machine but I wasn't aware :)
Sorry for that!

**Comment by Purfview** [comment]
> Lol you know what I do have NVIDIA GTX 1050 on windows host machine but I wasn't aware :)

2GB VRAM? Should be ~enough for medium model.
Download and place [cuBLAS and cuDNN libs](https://github.com/Purfview/whisper-standalone-win/releases/tag/libs)  at the executable .

**Comment by Purfview** [comment]
> TY this helped a lot! Could we mention this in the README for newcomers?

This is literally written at the Releases.

**Comment by NaiveInvestigator** [comment]
It is but for most ppl when they see the right side and tend to click on whisper-faster and not on the Releases link which leads them to the executables.
![image](https://github.com/Purfview/whisper-standalone-win/assets/72654596/ace4cc89-4f96-4f68-987c-42d4bb6d6d60)

**Comment by Purfview** [comment]
You see same info whatever you click there.

**Comment by Largo** [comment]
I'm on fedora 38. My research found that seemingly cuda and cuDNN are separate installs? I don't have the lib in /usr/local/cuda-12.4/lib64/.

So I did the following:

`sudo find / -type f -name libcudnn_ops_infer.so.8`

found it in /opt/resolve/libs/libcudnn_ops_infer.so.8

`export LD_LIBRARY_PATH="/opt/resolve/libs:$LD_LIBRARY_PATH"
`

And then it works!
