### ISSUE TITLE
5090 issue with CUDA: RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by redf0xx** [Purfview/whisper-standalone-win#433]
Edit2: Found a fix in the meantime while GPU issues are being sorted out: add `--diarize_device cpu` and `--vad_device cpu` to the cmd line and both VAD and diarization work again. It forces CPU usage for it and a little slower, but if you're trying to convert some things, it's not too bad.

Edit: It looks like the errors below happen when using diarization or VAD with a 5xxx series nvidia card. It seems that the current version is not updated with the latest version of torch that supports these new cards. Everything else works great when float16 or float32 is used as the compute type. It would be great to get this updated or be able to update the torch files somehow (confirmed working /w latest nightly version).

Log is below:

Standalone Faster-Whisper-XXL r245.2 running on: CUDA

Note: 'large-v3' model may produce worse results than 'large-v2'!

Speaker Diarization using Reverb v2: WavLM features

*** Legal notice: You shall only use the Rev Models and Outputs for testing, research, Personal, or evaluation purposes in Non-Production Environments. ***

Diarizing file: 'C:\Users\JJ\Downloads\Faster-Whisper-XXL_r245.2_windows\Faster-Whisper-XXL\01779ccd-4f6d-4697-81c9-9d585297c3c7.wav'
Traceback (most recent call last):
  File "D:\whisper-fast-XXL\__main__.py", line 2245, in <module>
  File "D:\whisper-fast-XXL\__main__.py", line 1925, in cli
  File "D:\whisper-fast-XXL\__main__.py", line 405, in get_diarization
  File "faster_whisper\diarization.py", line 71, in run_model
  File "faster_whisper\diarization.py", line 67, in _load_model
  File "pyannote\audio\core\pipeline.py", line 344, in to
  File "pyannote\audio\core\inference.py", line 192, in to
  File "lightning_fabric\utilities\device_dtype_mixin.py", line 55, in to
  File "torch\nn\modules\module.py", line 1152, in to
  File "torch\nn\modules\module.py", line 802, in _apply
  File "torch\nn\modules\rnn.py", line 221, in _apply
  File "torch\nn\modules\rnn.py", line 158, in _init_flat_weights
  File "torch\nn\modules\rnn.py", line 209, in flatten_parameters
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[PYI-21996:ERROR] Failed to execute script '__main__' due to unhandled exception!

**Comment by ricardogonzalezcases** [comment]
Same problem here!

**Comment by jarkkoilomaki** [comment]
Exactly the same problem, with diarization. Running on 5090

**Comment by Moeblack** [comment]
![Image](https://github.com/user-attachments/assets/9709432d-186e-489e-8109-726274532ebe)
 so bad same on 5090

**Comment by ricardogonzalezcases** [comment]
> ![Image](https://github.com/user-attachments/assets/9709432d-186e-489e-8109-726274532ebe) so bad same on 5090




Your problem fix with this parameter:  --compute_type float32


Our problem it's using diarization....

**Comment by Purfview** [comment]
> Same problem here! Only problem with diarization feature (reverb or pyannote)

Not only diarization, it affects all features that use torch.
PyTorch hasn't released a stable build that supports 50xx GPUs yet.

**Comment by Purfview** [comment]
Check the test build there: https://github.com/Purfview/whisper-standalone-win/issues/459

**Comment by ricardogonzalezcases** [comment]
it works now! thx very much

**Comment by theotherp** [comment]
> it works now! thx very much

What do you mean? PyTorch hasn't been update in the release Faster-Whisper-XXL r245.2. How did you get it to run?

**Comment by Purfview** [comment]
>What do you mean? PyTorch hasn't been update in the release Faster-Whisper-XXL r245.2. How did you get it to run?

He meant a test build he got to test.

I need to finish some things to make a release.

**Comment by jarkkoilomaki** [comment]
> > What do you mean? PyTorch hasn't been update in the release Faster-Whisper-XXL r245.2. How did you get it to run?
> 
> He meant a test build he got to test.
> 
> I need to finish some things to make a release.

Would the test build be available stil, (I would definitely like to test it with the diarization on 5090)?

**Comment by Knightchampion1** [comment]
Does anyone have a step by step solution to this yet?

**Comment by dlinford** [comment]
> > What do you mean? PyTorch hasn't been update in the release Faster-Whisper-XXL r245.2. How did you get it to run?
> 
> He meant a test build he got to test.
> 
> I need to finish some things to make a release.

Let us know when there is a release that works.

**Comment by Purfview** [comment]
I got carried away with various features that I didn't finish, I guess I need to rollback on things and just make a release.
Most likely it will be only a "Pro" release as a regular version needs things solved with GitHub's limits...

**Comment by dlinford** [comment]
That would be great.  What's the difference between "Pro" & "regular"?

**Comment by Purfview** [comment]
> That would be great. What's the difference between "Pro" & "regular"?

https://github.com/Purfview/whisper-standalone-win/discussions/456

**Comment by dlinford** [comment]
Thanks.  I'm in.

**Comment by dlinford** [comment]
Just put in £50.  Eagerly awaiting release that works with the 5090 / CUDA / Diarization.  

PS  Thanks for your work on this.  Amazing product.

**Comment by Edgaras91** [comment]
@Purfview, any ETA on this? Also, are you able to make this app open source?

**Comment by Purfview** [comment]
> Purfview, any ETA on this? 

~Few days, that's for Pro version, no ETA on regular version.

>Also, are you able to make this app open source?

No.

**Comment by funontheinternet** [comment]
> > Purfview, any ETA on this?
> 
> ~Few days, that's for Pro version, no ETA on regular version.
> 
> > Also, are you able to make this app open source?
> 
> No.

Hey, just checking if this had been updated for the 5090 GPUs?

**Comment by Purfview** [comment]
Should be fixed, currently in Pro r3.256.1
